# Generated by Django 4.0.3 on 2022-04-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='username',
        ),
        migrations.RemoveField(
            model_name='wishlistlisting',
            name='listingID',
        ),
        migrations.RemoveField(
            model_name='wishlistlisting',
            name='username',
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.user'),
        ),
        migrations.AddField(
            model_name='wishlistlisting',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.listing'),
        ),
        migrations.AddField(
            model_name='wishlistlisting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.user'),
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(to='server.tag'),
        ),
    ]
