# Generated by Django 4.0.3 on 2022-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
