# Generated by Django 4.0.3 on 2022-04-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_listing_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingID', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
