# Generated by Django 4.0.4 on 2022-04-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_user_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='...', max_length=255),
        ),
    ]
