# Generated by Django 4.0.3 on 2022-04-04 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_wishlistlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='username',
        ),
        migrations.RemoveField(
            model_name='wishlistlisting',
            name='listingID',
        ),
        migrations.RemoveField(
            model_name='wishlistlisting',
            name='username',
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
        migrations.AddField(
            model_name='wishlistlisting',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.listing'),
        ),
    ]
