# Generated by Django 4.0.4 on 2022-04-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.AddField(
            model_name='listing',
            name='username',
            field=models.CharField(default='...', max_length=255),
        ),
    ]
