# Generated by Django 4.0.3 on 2022-04-04 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_listing_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistlisting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
    ]
