# Generated by Django 4.0.4 on 2022-04-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_listing_user_listing_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='tags',
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.CharField(default='EMPTY', max_length=255),
        ),
    ]
