# Generated by Django 4.0.4 on 2022-04-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_listing_tags_listing_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistlisting',
            old_name='listingTitle',
            new_name='title',
        ),
    ]
