# Generated by Django 4.0.3 on 2022-04-08 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_tag_listing_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.listing'),
        ),
    ]
