# Generated by Django 4.0.3 on 2022-04-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_listing_tags_tag_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.ManyToManyField(to='webapp.tag'),
        ),
    ]
